memorydb/MemoryDbAspnet/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MemoryDbAspnet.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

memorydb/MemoryDbAspnet/Pages/Index.cshtml.cs
using MemoryDbAspnet.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Distributed;
using System.Diagnostics;
using System.Text.Json;

namespace MemoryDbAspnet.Pages;

public class IndexModel : PageModel
{
    public Stopwatch ServiceTimer { get; } = new Stopwatch();

    private readonly ILogger<IndexModel> _logger;
    private readonly IOrderService _svc;
    private readonly IDistributedCache _cache;


    // Properties for display
    public bool IsPopulated { get; set; }
    public string FirstLettter { get; set; }
    public decimal TotalCost { get; set; }
    public decimal NumOrders { get; set; }

    public IndexModel(ILogger<IndexModel> logger, IOrderService svc, IDistributedCache cache)
    {
        _logger = logger;
        _svc = svc;
        _cache = cache;
    }

    public async Task OnGetDataAsync(string q)
    {
        OrderServiceTotalResult result;

        // Retrieve the data for the display
        ServiceTimer.Start();

        //Updated cache retrieval logic
        var cachedData = await _cache.GetStringAsync(q);
        if (cachedData is null)
        {
            result = await _svc.GetOrdersForCustomerId(q);
            await _cache.SetStringAsync(q, JsonSerializer.Serialize(result),
                new DistributedCacheEntryOptions { SlidingExpiration = TimeSpan.FromSeconds(15) }
                );
        }
        else
        {
            result = JsonSerializer.Deserialize<OrderServiceTotalResult>(cachedData);
        }

        // Populate Page Data
        TotalCost = result.TotalCost;
        NumOrders = result.NumOrders;
        FirstLettter = q;
        IsPopulated = true;
        ServiceTimer.Stop();
    }

    public async Task OnGetAsync()
    {
        IsPopulated = false;
    }
}

memorydb/MemoryDbAspnet/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MemoryDbAspnet.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

memorydb/MemoryDbAspnet/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<p>
    Select the first letter of customer ID
</p>
<div class="d-grid gap-2 d-md-block">

    <a class="btn btn-primary" asp-route-q="0" asp-page-handler="data" as role="button">0</a>
    <a class="btn btn-primary" asp-route-q="1" asp-page-handler="data" as role="button">1</a>
    <a class="btn btn-primary" asp-route-q="2" asp-page-handler="data" as role="button">2</a>
    <a class="btn btn-primary" asp-route-q="3" asp-page-handler="data" as role="button">3</a>
    <a class="btn btn-primary" asp-route-q="4" asp-page-handler="data" as role="button">4</a>
    <a class="btn btn-primary" asp-route-q="5" asp-page-handler="data" as role="button">5</a>
    <a class="btn btn-primary" asp-route-q="6" asp-page-handler="data" as role="button">6</a>
    <a class="btn btn-primary" asp-route-q="7" asp-page-handler="data" as role="button">7</a>
    <a class="btn btn-primary" asp-route-q="8" asp-page-handler="data" as role="button">8</a>
    <a class="btn btn-primary" asp-route-q="9" asp-page-handler="data" as role="button">9</a>
    <a class="btn btn-primary" asp-route-q="a" asp-page-handler="data" as role="button">a</a>
    <a class="btn btn-primary" asp-route-q="b" asp-page-handler="data" as role="button">b</a>
    <a class="btn btn-primary" asp-route-q="c" asp-page-handler="data" as role="button">c</a>
    <a class="btn btn-primary" asp-route-q="d" asp-page-handler="data" as role="button">d</a>
    <a class="btn btn-primary" asp-route-q="e" asp-page-handler="data" as role="button">e</a>
    <a class="btn btn-primary" asp-route-q="f" asp-page-handler="data" as role="button">f</a>



</div>

@if (!Model.IsPopulated)
{
    <div class="row pt-3">
        <strong class="text-primary">Select a character above, to query all records where the customer ID matches that first letter</strong>
    </div>
}
else
{
    <div class="row col-6 pt-3">
        <strong class="text-success">Order Data Results</strong>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Letter</th>
                    <th scope="col">Orders</th>
                    <th scope="col">Total Cost</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td scope="row">@Model.FirstLettter</td>
                    <td scope="row">@Model.NumOrders</td>
                    <td scope="row">@string.Format("{0:C}", Model.TotalCost)</td>
                </tr>
            </tbody>

        </table>
        </div>
        <div>
        <hr />
        <p>
            It took <strong>@Model.ServiceTimer.ElapsedMilliseconds</strong> milliseconds to retrieve data.
        </p>


    </div>
}

memorydb/MemoryDbAspnet/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MemoryDbAspnet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MemoryDbAspnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MemoryDbAspnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MemoryDbAspnet - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>